### ISSUE TITLE
Conformal risk control question

### ISSUE THREAD

**Issue by harryzhangOG** [aangelopoulos/conformal-prediction#13]
Hi, thank you so much for the great work. I have a question regarding the notebook on conformal risk control.

in the notebook, you defined the risk optimization objective as 
```Python
def lamhat_threshold(lam): return false_negative_rate(cal_sgmd>=lam, cal_gt_masks) - ((n+1)/n*alpha - 1/(n+1))
```
However, in section 4.3 of the paper, it is defined as $$\alpha - \frac{B-\alpha}{n}$$, which means the denominator should be $n$. Why is it $n+1$ in the code? Thanks.

**Comment by aangelopoulos** [comment]
Ah --- these two are equivalent! Try writing it out and let me know if you
see it ;)

Best,
Anastasios Angelopoulos
https://people.eecs.berkeley.edu/~angelopoulos/

**Comment by aangelopoulos** [comment]
Ah - sorry, don't want to leave this unfinished. Actually, it should be true with equality, and I think you may have caught a bug. Here's the derivation:

(n+1)/n*alpha - 1/n
= alpha + (1/n)alpha - 1/n
= alpha - ((1-alpha)/n)

So, you're right! Thanks so much!

Maybe you should make a PR? That way you'll get some credit 😀 

Otherwise if I don't hear from you, I'll just fix it myself soon.  Thanks so much again!!

**Comment by 601SunG** [comment]
> Ah - sorry, don't want to leave this unfinished. Actually, it should be true with equality, and I think you may have caught a bug. Here's the derivation:
> 
> (n+1)/n*alpha - 1/n = alpha + (1/n)alpha - 1/n = alpha - ((1-alpha)/n)
> 
> So, you're right! Thanks so much!
> 
> Maybe you should make a PR? That way you'll get some credit 😀
> 
> Otherwise if I don't hear from you, I'll just fix it myself soon. Thanks so much again!!

Thanks Anastasios, but I think you made a typo, the derivation should start from (n+1)/n*alpha - 1/(n+1), as shown in code

**Comment by aangelopoulos** [comment]
I was proving that the code is wrong! 😀 

It should be what I said in my message. The expression I started with is the correct version.
